#:schema node_modules/wrangler/config-schema.json
name = "article-to-pdf"
main = "src/index.ts"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

[browser]
binding = "PDF_BROWSER"

[durable_objects]
bindings = [
  { name = "BROWSER_DO", class_name = "BrowserSession" }
]

[[migrations]]
tag = "v1-init-do" # Give it a unique tag
new_classes = ["BrowserSession"] # List the NEW Durable Object classes being introduced

